import { useAction } from "convex/react";
import { api } from "../../../convex/_generated/api";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { Textarea } from "../ui/textarea";
import { useState } from "react";
import { cn } from "../../lib/utils";
import { User, Mail, MapPin, Users, HeartHandshake, CheckCircle2, ChevronRight, Phone, Contact, Camera, Lock, UserPlus } from "lucide-react";

// Zod Schema (Password removed)
const schema = z.object({
    name: z.string().min(2, "Naam is verplicht"),
    email: z.string().email("Ongeldig email adres"),
    role: z.enum(["deelnemer", "begeleider", "vrijwilliger"], {
        required_error: "Kies een rol",
    }),
    distance: z.enum(["2.5", "6", "10", "15"], {
        required_error: "Kies een afstand"
    }),
    supportNeeded: z.enum(["ja", "nee", "anders"], {
        required_error: "Maak een keuze"
    }),
    agreedToTerms: z.literal(true, {
        errorMap: () => ({ message: "Je moet akkoord gaan met de voorwaarden" }),
    }),
    // Password fields removed from validation
    supportDescription: z.string().optional(),
    iceName: z.string().min(2, "Naam contactpersoon is verplicht"),
    icePhone: z.string().min(10, "Geldig telefoonnummer is verplicht"),
    agreedToMedia: z.boolean().optional(),
}).refine((data) => {
    if (data.supportNeeded === "anders") return !!data.supportDescription && data.supportDescription.length > 0;
    return true;
}, {
    message: "Licht je keuze toe",
    path: ["supportDescription"]
});

type FormData = z.infer<typeof schema>;

export default function RegisterForm() {
    const registerParticipant = useAction(api.register.registerParticipant);
    const registerGuest = useAction(api.registerGuest.registerGuest);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [wantsAccount, setWantsAccount] = useState(false); // Guest by default

    const {
        register,
        handleSubmit,
        watch,
        setValue,
        formState: { errors },
    } = useForm<FormData>({
        resolver: zodResolver(schema),
        defaultValues: {
            supportNeeded: "nee",
            role: "deelnemer",
            agreedToMedia: false,
        }
    });

    const selectedRole = watch("role");
    const selectedDistance = watch("distance");
    const selectedSupport = watch("supportNeeded");

    const onSubmit = async (data: FormData) => {
        setIsSubmitting(true);
        setError(null);

        try {
            if (wantsAccount) {
                // Authenticated flow: create account via LaventeCare Auth
                const autoGeneratedPassword = crypto.randomUUID() + "-" + Math.random().toString(36).slice(2) + "A!1";

                await registerParticipant({
                    name: data.name,
                    email: data.email,
                    role: data.role,
                    distance: data.distance,
                    supportNeeded: data.supportNeeded,
                    supportDescription: data.supportDescription,
                    iceName: data.iceName,
                    icePhone: data.icePhone,
                    agreedToTerms: data.agreedToTerms,
                    agreedToMedia: !!data.agreedToMedia,
                    password: autoGeneratedPassword,
                });

                // Trigger Password Reset Email (To set initial password)
                try {
                    await fetch('/api/v1/auth/password/forgot', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ email: data.email })
                    });
                } catch (e) {
                    console.error("Failed to send password reset email", e);
                }

                // Redirect to login
                window.location.href = "/login?registered=true";
            } else {
                // Guest flow: no account, direct registration
                await registerGuest({
                    name: data.name,
                    email: data.email,
                    role: data.role,
                    distance: data.distance,
                    supportNeeded: data.supportNeeded,
                    supportDescription: data.supportDescription,
                    iceName: data.iceName,
                    icePhone: data.icePhone,
                    agreedToTerms: data.agreedToTerms,
                    agreedToMedia: !!data.agreedToMedia,
                });

                // Trigger Welcome Email
                try {
                    await fetch('/api/v1/auth/register-confirmation', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ name: data.name, email: data.email })
                    });
                } catch (e) {
                    console.error("Failed to send welcome email", e);
                }

                // Redirect to success page (no login)
                window.location.href = "/registratie-succes";
            }
        } catch (err: any) {
            console.error(err);
            let errorMessage = err.message || "Er is iets misgegaan bij het registreren.";

            // Strip Convex wrapper text to show only our custom message
            if (errorMessage.includes("Dit e-mailadres is al bekend")) {
                errorMessage = "Dit e-mailadres is al bekend. Log in of gebruik een ander adres.";
            } else if (errorMessage.includes("Dit e-mailadres is al in gebruik")) {
                errorMessage = "Dit e-mailadres is al in gebruik.";
            }

            setError(errorMessage);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-8 max-w-3xl mx-auto">
            {error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl text-sm text-center animate-fade-in flex items-center justify-center gap-2">
                    <span className="text-lg">⚠️</span> {error}
                </div>
            )}

            {/* 1. Contactgegevens */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2.5 bg-brand-orange/10 rounded-xl text-brand-orange">
                        <User className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold font-display text-text-body">Je contactgegevens</h3>
                        <p className="text-sm text-text-muted">Vul je gegevens in om je aan te melden.</p>
                    </div>
                </div>

                <div className="space-y-4">
                    <div className="space-y-2 group/field">
                        <Label htmlFor="name" className="transition-colors group-hover/field:text-brand-orange">Naam</Label>
                        <div className="relative transition-all duration-300">
                            <User className="absolute left-3.5 top-3.5 h-5 w-5 text-text-muted/50 transition-colors duration-300 group-focus-within/field:text-brand-orange group-hover/field:text-brand-orange/70" />
                            <Input id="name" {...register("name")} placeholder="Vul je volledige naam in" className="pl-11 transition-all duration-300 group-focus-within/field:ring-brand-orange/50 group-focus-within/field:border-brand-orange group-focus-within/field:shadow-[0_0_20px_-5px_rgba(255,147,40,0.3)] group-hover/field:border-brand-orange/50 group-hover/field:shadow-[0_0_15px_-5px_rgba(255,147,40,0.2)] hover:bg-brand-orange/5" />
                        </div>
                        {errors.name && <p className="text-red-400 text-xs pl-1">{errors.name?.message}</p>}
                    </div>

                    <div className="space-y-2 group/field">
                        <Label htmlFor="email" className="transition-colors group-hover/field:text-brand-orange">E-mailadres</Label>
                        <div className="relative transition-all duration-300">
                            <Mail className="absolute left-3.5 top-3.5 h-5 w-5 text-text-muted/50 transition-colors duration-300 group-focus-within/field:text-brand-orange group-hover/field:text-brand-orange/70" />
                            <Input id="email" type="email" {...register("email")} placeholder="jouw.email@example.com" className="pl-11 transition-all duration-300 group-focus-within/field:ring-brand-orange/50 group-focus-within/field:border-brand-orange group-focus-within/field:shadow-[0_0_20px_-5px_rgba(255,147,40,0.3)] group-hover/field:border-brand-orange/50 group-hover/field:shadow-[0_0_15px_-5px_rgba(255,147,40,0.2)] hover:bg-brand-orange/5" />
                        </div>
                        {errors.email && <p className="text-red-400 text-xs pl-1">{errors.email?.message}</p>}
                    </div>
                </div>
            </div>

            {/* 2. Kies je rol */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2.5 bg-brand-orange/10 rounded-xl text-brand-orange">
                        <Users className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold font-display text-text-body">Kies je rol</h3>
                        <p className="text-sm text-text-muted">Hoe wil je meedoen aan het evenement?</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {[
                        { id: "deelnemer", label: "Deelnemer", icon: "🏃", desc: "Ik loop mee" },
                        { id: "begeleider", label: "Begeleider", icon: "🤝", desc: "Ik begeleid iemand" },
                        { id: "vrijwilliger", label: "Vrijwilliger", icon: "💪", desc: "Ik help mee" }
                    ].map((role) => (
                        <div
                            key={role.id}
                            onClick={() => setValue("role", role.id as any)}
                            className={cn(
                                "cursor-pointer rounded-2xl border-2 p-4 text-center transition-all duration-300 relative group overflow-hidden",
                                selectedRole === role.id
                                    ? "border-brand-orange bg-brand-orange/5 shadow-lg scale-[1.05]"
                                    : "border-border glass-card hover:border-brand-orange/50"
                            )}
                        >
                            {selectedRole === role.id && (
                                <div className="absolute inset-0 bg-linear-to-tr from-brand-orange/10 to-transparent pointer-events-none" />
                            )}
                            {selectedRole === role.id && (
                                <div className="absolute top-2 right-2 text-brand-orange animate-in fade-in zoom-in duration-300">
                                    <CheckCircle2 className="w-4 h-4 fill-brand-orange/20" />
                                </div>
                            )}
                            <div className="text-3xl mb-3 transform group-hover:scale-110 group-hover:rotate-3 transition-transform duration-300 filter drop-shadow-md">{role.icon}</div>
                            <div className={cn("font-bold text-lg transition-colors duration-300", selectedRole === role.id ? "text-brand-orange" : "text-text-body")}>
                                {role.label}
                            </div>
                            <div className="text-xs text-text-muted mt-1 group-hover:text-text-body transition-colors">{role.desc}</div>
                        </div>
                    ))}
                </div>
                {errors.role && <p className="text-red-400 text-xs pl-1">{errors.role?.message}</p>}
            </div>

            {/* 3. Kies je afstand */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2.5 bg-blue-500/10 rounded-xl text-blue-500">
                        <MapPin className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold font-display text-text-body">Kies je afstand</h3>
                        <p className="text-sm text-text-muted">Welke route ga je lopen?</p>
                    </div>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {[
                        { id: "2.5", label: "2.5 KM", icon: "🚶", color: "text-green-500" },
                        { id: "6", label: "6 KM", icon: "🏃", color: "text-blue-500" },
                        { id: "10", label: "10 KM", icon: "🏃‍♂️", color: "text-purple-500" },
                        { id: "15", label: "15 KM", icon: "🏃‍♀️", color: "text-orange-500" }
                    ].map((dist) => (
                        <div
                            key={dist.id}
                            onClick={() => setValue("distance", dist.id as any)}
                            className={cn(
                                "cursor-pointer rounded-2xl border-2 p-4 text-center transition-all duration-300 relative group overflow-hidden",
                                selectedDistance === dist.id
                                    ? "border-brand-orange bg-brand-orange/5 shadow-lg scale-[1.05]"
                                    : "border-border glass-card hover:border-brand-orange/50"
                            )}
                        >
                            {selectedDistance === dist.id && (
                                <div className="absolute inset-0 bg-linear-to-tr from-brand-orange/10 to-transparent pointer-events-none" />
                            )}
                            {selectedDistance === dist.id && (
                                <div className="absolute top-2 right-2 text-brand-orange animate-in fade-in zoom-in duration-300">
                                    <CheckCircle2 className="w-4 h-4 fill-brand-orange/20" />
                                </div>
                            )}
                            <div className="text-2xl mb-2 transform group-hover:scale-110 group-hover:-rotate-3 transition-transform duration-300 filter drop-shadow-md">{dist.icon}</div>
                            <div className={cn("font-bold text-lg transition-colors duration-300", selectedDistance === dist.id ? "text-brand-orange" : "text-text-body")}>
                                {dist.label}
                            </div>
                        </div>
                    ))}
                </div>
                {errors.distance && <p className="text-red-400 text-xs pl-1">{errors.distance?.message}</p>}
            </div>

            {/* 4. Ondersteuning */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2.5 bg-brand-orange/10 rounded-xl text-brand-orange">
                        <HeartHandshake className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold font-display text-text-body">Ondersteuning</h3>
                        <p className="text-sm text-text-muted">Heb je extra hulp nodig tijdens het evenement?</p>
                    </div>
                </div>

                <div className="grid grid-cols-3 gap-4">
                    {[
                        { id: "ja", label: "Ja, graag", icon: "✅" },
                        { id: "nee", label: "Nee", icon: "❌" },
                        { id: "anders", label: "Anders", icon: "❓" }
                    ].map((opt) => (
                        <div
                            key={opt.id}
                            onClick={() => setValue("supportNeeded", opt.id as any)}
                            className={cn(
                                "cursor-pointer rounded-2xl border-2 p-4 text-center transition-all duration-300 relative group overflow-hidden",
                                selectedSupport === opt.id
                                    ? "border-brand-primary bg-brand-primary/5 shadow-lg scale-[1.05]"
                                    : "border-border glass-card hover:border-brand-orange/50"
                            )}
                        >
                            {selectedSupport === opt.id && (
                                <div className="absolute inset-0 bg-linear-to-tr from-brand-primary/10 to-transparent pointer-events-none" />
                            )}
                            {selectedSupport === opt.id && (
                                <div className="absolute top-2 right-2 text-brand-primary animate-in fade-in zoom-in duration-300">
                                    <CheckCircle2 className="w-4 h-4 fill-brand-orange/20" />
                                </div>
                            )}
                            <div className="text-2xl mb-2 transform group-hover:scale-110 group-hover:-rotate-3 transition-transform duration-300 filter drop-shadow-md">{opt.icon}</div>
                            <div className={cn("font-bold text-lg transition-colors duration-300", selectedSupport === opt.id ? "text-brand-orange" : "text-text-body")}>
                                {opt.label}
                            </div>
                        </div>
                    ))}
                </div>

                {selectedSupport === "anders" && (
                    <div className="animate-fade-in origin-top group transition-all duration-300">
                        <Label htmlFor="supportDescription" className="mb-2 block cursor-pointer">Toelichting</Label>
                        <Textarea
                            id="supportDescription"
                            {...register("supportDescription")}
                            placeholder="Waar kunnen we je mee helpen?"
                            className="min-h-[100px] bg-glass-bg focus-visible:ring-brand-orange/50 focus-visible:border-brand-orange shadow-sm hover:bg-brand-orange/5 transition-all"
                        />
                        {errors.supportDescription && <p className="text-red-400 text-xs pl-1 mt-1">{errors.supportDescription?.message}</p>}
                    </div>
                )}
            </div>

            {/* 5. Noodcontact (ICE) */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2.5 bg-brand-orange/10 rounded-xl text-brand-orange">
                        <Phone className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold font-display text-text-body">Noodcontact (ICE)</h3>
                        <p className="text-sm text-text-muted">Wie kunnen we bellen in geval van nood?</p>
                    </div>
                </div>

                <div className="space-y-4">
                    <div className="space-y-2 group/field">
                        <Label htmlFor="iceName" className="transition-colors group-hover/field:text-brand-orange">Naam contactpersoon</Label>
                        <div className="relative transition-all duration-300">
                            <Contact className="absolute left-3.5 top-3.5 h-5 w-5 text-text-muted transition-colors duration-300 group-focus-within/field:text-brand-orange group-hover/field:text-brand-orange/70 group-hover/field:scale-110 transform" />
                            <Input id="iceName" {...register("iceName")} placeholder="Naam van partner, ouder, vriend..." className="pl-11 transition-all duration-300 group-focus-within/field:bg-transparent group-focus-within/field:ring-brand-orange/50 group-focus-within/field:border-brand-orange group-focus-within/field:shadow-[0_0_20px_-5px_rgba(255,147,40,0.3)] group-hover/field:border-brand-orange/50 group-hover/field:shadow-[0_0_15px_-5px_rgba(255,147,40,0.2)] hover:bg-brand-orange/5" />
                        </div>
                        {errors.iceName && <p className="text-red-400 text-xs pl-1">{errors.iceName?.message}</p>}
                    </div>

                    <div className="space-y-2 group/field">
                        <Label htmlFor="icePhone" className="transition-colors group-hover/field:text-brand-orange">Telefoonnummer</Label>
                        <div className="relative transition-all duration-300">
                            <Phone className="absolute left-3.5 top-3.5 h-5 w-5 text-text-muted transition-colors duration-300 group-focus-within/field:text-brand-orange group-hover/field:text-brand-orange/70 group-hover/field:scale-110 transform" />
                            <Input id="icePhone" type="tel" {...register("icePhone")} placeholder="06 12345678" className="pl-11 transition-all duration-300 group-focus-within/field:bg-transparent group-focus-within/field:ring-brand-orange/50 group-focus-within/field:border-brand-orange group-focus-within/field:shadow-[0_0_20px_-5px_rgba(255,147,40,0.3)] group-hover/field:border-brand-orange/50 group-hover/field:shadow-[0_0_15px_-5px_rgba(255,147,40,0.2)] hover:bg-brand-orange/5" />
                        </div>
                        {errors.icePhone && <p className="text-red-400 text-xs pl-1">{errors.icePhone?.message}</p>}
                    </div>
                </div>
            </div>

            {/* 5.5 Account Toggle */}
            <div className="space-y-6 bg-linear-to-br from-brand-orange/5 to-transparent p-6 rounded-2xl border border-brand-orange/20">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2.5 bg-brand-orange/10 rounded-xl text-brand-orange">
                        <UserPlus className="w-6 h-6" />
                    </div>
                    <div>
                        <h3 className="text-xl font-bold font-display text-text-body">Account aanmaken (optioneel)</h3>
                        <p className="text-sm text-text-muted">Kies hoe je wilt deelnemen</p>
                    </div>
                </div>

                <div className="space-y-4">
                    <div className="flex items-start gap-4 p-4 glass-card border border-border hover:border-brand-orange/30 transition-all cursor-pointer" onClick={() => setWantsAccount(!wantsAccount)}>
                        <div className="pt-1">
                            <input
                                type="checkbox"
                                checked={wantsAccount}
                                onChange={(e) => setWantsAccount(e.target.checked)}
                                className="h-5 w-5 rounded border-glass-border bg-glass-bg text-brand-orange focus:ring-brand-orange cursor-pointer"
                            />
                        </div>
                        <div className="space-y-2 flex-1">
                            <Label className="text-text-body font-bold cursor-pointer flex items-center gap-2">
                                <Lock className="w-4 h-4" />
                                Ik wil een account aanmaken voor toekomstige edities
                            </Label>
                            {wantsAccount && (
                                <div className="text-sm space-y-1 p-3 bg-brand-orange/5 rounded-lg border border-brand-orange/20 animate-fade-in">
                                    <p className="text-text-muted font-medium">✅ Voordelen van een account:</p>
                                    <ul className="text-text-muted text-xs space-y-1 pl-4">
                                        <li>• Toegang tot je persoonlijke dashboard</li>
                                        <li>• Beheer inschrijvingen voor meerdere jaren</li>
                                        <li>• Sneller inschrijven voor volgende edities</li>
                                        <li>• Ontvang updates over je deelname</li>
                                    </ul>
                                </div>
                            )}
                            {!wantsAccount && (
                                <p className="text-sm text-text-muted">
                                    Je schrijft je alleen in voor dit evenement, zonder account.
                                </p>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* 6. Voorwaarden & Submit */}
            <div className="space-y-6 pt-6 border-t border-glass-border">
                <h3 className="text-lg font-bold font-display text-text-body">Afronden</h3>

                <div className="bg-surface/50 p-4 rounded-xl border border-glass-border space-y-4">
                    {/* Terms */}
                    <div className="flex items-start gap-4">
                        <div className="pt-1">
                            <input
                                type="checkbox"
                                id="terms"
                                {...register("agreedToTerms")}
                                className="h-5 w-5 rounded border-glass-border bg-glass-bg text-brand-primary focus:ring-brand-primary cursor-pointer"
                            />
                        </div>
                        <div className="space-y-1">
                            <Label htmlFor="terms" className="text-text-body font-bold cursor-pointer">
                                Akkoord met de voorwaarden
                            </Label>
                            <p className="text-sm text-text-muted">
                                Ik heb de <a href="#" className="text-brand-primary hover:underline font-medium">Algemene Voorwaarden</a> gelezen en ga hiermee akkoord.
                            </p>
                        </div>
                    </div>
                    {errors.agreedToTerms && <p className="text-red-400 text-xs mt-2 pl-9">{errors.agreedToTerms?.message}</p>}

                    {/* Media Consent */}
                    <div className="flex items-start gap-4 pt-4 border-t border-glass-border/50">
                        <div className="pt-1">
                            <input
                                type="checkbox"
                                id="media"
                                {...register("agreedToMedia")}
                                className="h-5 w-5 rounded border-glass-border bg-glass-bg text-brand-primary focus:ring-brand-primary cursor-pointer"
                            />
                        </div>
                        <div className="space-y-1">
                            <Label htmlFor="media" className="text-text-body font-bold cursor-pointer flex items-center gap-2">
                                <Camera className="w-4 h-4 text-text-muted" /> Foto's & Video
                            </Label>
                            <p className="text-sm text-text-muted">
                                Ik vind het goed dat er tijdens het evenement beelden worden gemaakt voor promotie.
                            </p>
                        </div>
                    </div>
                </div>

                <Button
                    type="submit"
                    variant="default"
                    className="w-full bg-brand-orange text-white shadow-2xl shadow-brand-orange/30 h-14 text-lg rounded-2xl group transition-all duration-500 hover:scale-[1.02] hover:shadow-brand-orange/50 hover:bg-brand-orange/90 relative overflow-hidden"
                    disabled={isSubmitting}
                >
                    <div className="absolute inset-0 bg-linear-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:animate-[shimmer_1.5s_infinite]" />
                    {isSubmitting ? (
                        "Bezig met verwerken..."
                    ) : (
                        <span className="flex items-center gap-2 relative z-10">
                            {wantsAccount ? "Account Aanmaken & Inschrijven" : "Nu Inschrijven (Zonder Account)"} <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                        </span>
                    )}
                </Button>

                {/* Info about chosen flow */}
                <p className="text-xs text-text-muted text-center">
                    {wantsAccount
                        ? "Je ontvangt een email om je wachtwoord in te stellen."
                        : "Je kunt later nog een account aanmaken via 'Mijn Deelname'."}
                </p>
            </div>
        </form>
    );
}
